import tests.functions as functions

if __name__ == "__main__":
    #    functions.validate_all_redirects("linked.data.gov.au-vocabularies.json")

    conf = open("../conf/linked.data.gov.au-vocabularies.conf")
    new = [
        "anzsrc-for",
        "anzsrc-seo",
        "ausplots-cv",
        "australian-phone-area-codes",
        "care",
        "corveg-cv",
        "nrm",
        "reg-roles",
        "reg-statuses",
        "address-type",
        "australian-states-and-territories",
        "bc-labels",
        "data-access-rights",
        "dataciteroles",
        "depth-reference",
        "geo-commodities",
        "geoadminfeatures",
        "geofeatures",
        "geological-observation-instrument",
        "geological-observation-method",
        "geological-observation-type",
        "geological-sites",
        "geometry-roles",
        "georesource-report",
        "gsq-alias",
        "gsq-dataset-theme",
        "gsq-roles",
        "gsq-sample-facility",
        "iso639-1",
        "iso-19157-data-quality-dimension",
        "iso-iec-25012-data-quality-dimension",
        "nsw-quality-dimension",
        "party-identifier-type",
        "qg-agent",
        "qg-file-types",
        "qg-security-classifications",
        "qg-sites",
        "qld-data-licenses",
        "iso19115-1/RoleCode",
        "minerals",
        "nslvoc",
        "observation-detail-type",
        "organisation-activity-status",
        "organisation-name-types",
        "organisation-type",
        "party-relationship",
        "queensland-crs",
        "qld-resource-permit-status",
        "qld-resource-permit",
        "qld-utm-zones",
        "geou",
        "iso11179-6/RolesAndResponsibilities",
        "qesd-qkd",
        "qesd-uom",
        "qld-obsprop",
        "report-detail-type",
        "report-status",
        "resource-project-lifecycle",
        "resource-types",
        "result-type",
        "sample-detail-type",
        "sample-location-status",
        "sample-location-types",
        "sample-material",
        "sample-preparation-methods",
        "sample-relationship",
        "sample-type",
        "seismic-dimensionality",
        "site-detail-type",
        "site-relationships",
        "site-status",
        "supermodel/terms",
        "survey-detail-type",
        "survey-method",
        "survey-relationship-type",
        "survey-status",
        "survey-type",
        "telephone-type",
        "tk-labels",
        "trs"
    ]
    lines = conf.readlines()

    for n in new:
        for line in lines:
            if n in line:
                pattern, match = line.split("$", 1)
                print(pattern.strip().replace("RewriteRule ^", "https://linked.data.gov.au/"), " -- ", match.split("[R")[0].replace('"', '').strip())
                break